server:
  port: 9100

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zyd-cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: ExpendHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jta:
    atomikos:
      datasource:
        max-pool-size: 10
  #activiti
  activiti:
    check-process-definitions: false
    async-executor-activate: true
    database-schema-update: true
    db-history-used: true
    history-level: FULL
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
ribbon:
  eager-load:
    enabled: true
    clients: zyd-demo
  #请求处理的超时时间
  ReadTimeout: 4000
  #请求连接的超时时间
  ConnectTimeout: 4000
#端点监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  sentinel:
    enabled: true
#安全配置
security:
  oauth2:
    resource:
      id: zyd-demo
      #指定用户信息地址
      user-info-uri: http://127.0.0.1/api/auth/user
      prefer-token-info: false
